_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "ResNet-18"
  WEIGHTS: "torchvision://ResNet-18"
  NUM_CLASSES: 3
  MASK_ON: True
  ROI_HEADS:
    NAME: "CascadeROIHeads"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN: ("fruits_nuts", )
  TEST: ("fruits_nuts", )
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  MAX_ITER: 300
  STEPS: (200, 250)
  WARMUP_ITERS: 1
  CHECKPOINT_PERIOD: 300
TEST:
  EVAL_PERIOD: 300
OUTPUT_DIR: "output/getting_start/cascade_rcnn_resnet_18_fpn_3x"
