_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "torchvision://ResNet-18"
  MASK_ON: True
  NUM_CLASSES: 3
  BACKBONE:
    NAME: "ResNet-18"
DATASETS:
  TRAIN: ("fruits_nuts", )
  TEST: ("fruits_nuts", )
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  MAX_ITER: 300
  STEPS: (200, 250)
  WARMUP_ITERS: 1
  CHECKPOINT_PERIOD: 300
TEST:
  EVAL_PERIOD: 300
OUTPUT_DIR: "output/getting_start/mask_rcnn_resnet_18_fpn_3x"
