from fvcore.common.config import CfgNode as CN


def add_pointrend_config(cfg):
    cfg.MODEL.ROI_MASK_HEAD.IN_FEATURES = ("p2",)

    cfg.MODEL.ROI_MASK_HEAD.FC_DIM = 1024

    cfg.MODEL.ROI_MASK_HEAD.NUM_FC = 2

    cfg.MODEL.ROI_MASK_HEAD.OUTPUT_SIDE_RESOLUTION = 7

    cfg.MODEL.ROI_MASK_HEAD.POINT_HEAD_ON = False

    cfg.MODEL.POINT_HEAD = CN()

    cfg.MODEL.POINT_HEAD.NAME = "StandardPointHead"

    cfg.MODEL.POINT_HEAD.IN_FEATURES = ("p2",)

    cfg.MODEL.POINT_HEAD.TRAIN_NUM_POINTS = 14 * 14

    cfg.MODEL.POINT_HEAD.OVERSAMPLE_RATIO = 3

    cfg.MODEL.POINT_HEAD.IMPORTANCE_SAMPLE_RATIO = 0.75

    cfg.MODEL.POINT_HEAD.SUBDIVISION_STEPS = 5

    cfg.MODEL.POINT_HEAD.SUBDIVISION_NUM_POINTS = 28 * 28

    cfg.MODEL.POINT_HEAD.FC_DIM = 256

    cfg.MODEL.POINT_HEAD.NUM_FC = 3

    cfg.MODEL.POINT_HEAD.CLS_AGNOSTIC_MASK = False

    cfg.MODEL.POINT_HEAD.COARSE_PRED_EACH_LAYER = True
