MODEL:
  META_ARCHITECTURE: "RetinaNet"
  WEIGHTS: "torchvision://ResNet-50"
  NUM_CLASSES: 80
  BACKBONE:
    NAME: "ResNet-50"
    OUT_FEATURES: ["layer2", "layer3", "layer4"]
  NECK:
    ENABLE: True
    NAME: "FPN"
  ANCHOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
RESNET:
  NORM: "BN"
  REPLACE_STRIDE_WITH_DILATION: [False, False, False]
FPN:
  IN_FEATURES: ["layer2", "layer3", "layer4"]
  TOP_BLOCK:
    NAME: "LastLevelP6P7"
    IN_FEATURE: "layer4"
RETINANET:
  IOU_THRESHOLDS: [0.4, 0.5]
  IOU_LABELS: [0, -1, 1]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 500
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
