MODEL:
  META_ARCHITECTURE: "SSD"
  NUM_CLASSES: 80
  BACKBONE:
    NAME: "VGG-16"
    OUT_FEATURES: ["12", "19"]
  NECK:
    NAME: "VGGExtraLayers"
  ANCHOR:
    NAME: "SSDAnchorGenerator"
    SIZES: [30, 60, 111, 162, 213, 264, 315]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    OFFSET: 0.5
SSD:
  STRIDES: [8, 16, 32, 64, 100, 300]
  
INPUT:
  TRANSFORM: "ResizeTransform"
  MAX_SIZE_TRAIN: 300
  MAX_SIZE_TEST: 300
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 500