MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "torchvision://ResNet-50"
  NUM_CLASSES: 80
  BACKBONE:
    NAME: "ResNet-50"
    OUT_FEATURES: ["layer1", "layer2", "layer3", "layer4"]
  NECK:
    ENABLE: True
    NAME: "FPN"
  ANCHOR:
    SIZES: [[32], [64], [128], [256], [512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
FPN:
  IN_FEATURES: ["layer1", "layer2", "layer3", "layer4"]
  TOP_BLOCK:
    NAME: "LastLevelMaxPool"
    IN_FEATURE: "p5"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
