MODEL:
  META_ARCHITECTURE: "SSD"
  NUM_CLASSES: 80
  WEIGHTS: "torchvision://MobileNet-V2-1.0"
  BACKBONE:
    NAME: "MobileNet-V2-1.0"
    OUT_FEATURES: ["13", "18"]
  NECK:
    NAME: "SSDLiteExtraLayers"
  ANCHOR:
    NAME: "SSDAnchorGenerator"
    SIZES: [60, 105, 150, 195, 240, 285, 330]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    OFFSET: 0.5
SSD:
  STRIDES: [16, 32, 64, 107, 160, 320]
  HEAD:
    NAME: "SSDLiteHead"
    NORM: "BN"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  FORMAT: "RGB"
  TRANSFORM: "SSDTransform"
  MAX_SIZE_TRAIN: 320
  MAX_SIZE_TEST: 320
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.001
  MAX_ITER: 400000
  STEPS: [280000, 360000]
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
