_BASE_: "../Base-FCOS.yaml"
MODEL:
  WEIGHTS: "torchvision://ResNet-50"
  NUM_CLASSES: 10
  BACKBONE:
    NAME: "ResNet-50"
    OUT_FEATURES: ["layer2", "layer3", "layer4"]
FPN:
  IN_FEATURES: ["layer2", "layer3", "layer4"]
  TOP_BLOCK:
    NAME: "LastLevelP6P7"
    IN_FEATURE: "p5"
FCOS:
  NORM_REG_TARGETS: True
  CENTERNESS_ON_REG: True
  CENTER_SAMPLING_RADIUS: 1.5
  NUM_CONVS: 4
DATASETS:
  TRAIN: ("vis_2018_train",)
  TEST: ("vis_2018_val",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 57600
  STEPS: (38400, 52800)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1600
TEST:
  EVAL_PERIOD: 1600
INPUT:
  TRANSFORM: "ResizeTransform"
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "output/visdrone/fcos_resnet_50_fpn_3x"
