_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "torchvision://ResNet-101"
  NUM_CLASSES: 10
  BACKBONE:
    NAME: "ResNet-101"
DATASETS:
  TRAIN: ("vis_2018_train",)
  TEST: ("vis_2018_val",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 57600
  STEPS: (38400, 52800)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1600
TEST:
  EVAL_PERIOD: 1600
INPUT:
  TRANSFORM: "ResizeTransform"
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "output/visdrone/retinanet_resnet_101_fpn_3x"
