_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "torchvision://ShuffleNet-V2-1.0"
  BACKBONE:
    NAME: "ShuffleNet-V2-1.0"
    OUT_FEATURES: ["stage2", "stage3", "conv5"]
  NUM_CLASSES: 10
SHUFFLENET_V2:
  NORM: "BN"
FPN:
  IN_FEATURES: ["stage2", "stage3", "conv5"]
  TOP_BLOCK:
    IN_FEATURE: "conv5"
DATASETS:
  TRAIN: ("vis_2018_train",)
  TEST: ("vis_2018_val",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 57600
  STEPS: (38400, 52800)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1600
TEST:
  EVAL_PERIOD: 1600
OUTPUT_DIR: "output/visdrone/retinanet_shufflenet_v2_1_0_fpn_3x"
