MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "torchvision://ResNet-50"
  NUM_CLASSES: 20
  BACKBONE:
    NAME: "ResNet-50"
    OUT_FEATURES: ["layer1", "layer2", "layer3", "layer4"]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 144000
  STEPS: (96000, 132000)
  WARMUP_ITERS: 500
INPUT:
  TRANSFORM: "ResizeTransform"
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "output/pascal_voc/faster_rcnn_resnet_50_fpn_3x.yaml"
