_BASE_: "../Base-FCOS.yaml"
MODEL:
  WEIGHTS: "torchvision://ResNet-18"
  NUM_CLASSES: 20
  BACKBONE:
    NAME: "ResNet-18"
    OUT_FEATURES: ["layer2", "layer3", "layer4"]
FPN:
  IN_FEATURES: ["layer2", "layer3", "layer4"]
  TOP_BLOCK:
    NAME: "LastLevelP6P7"
    IN_FEATURE: "p5"
FCOS:
  NORM_REG_TARGETS: True
  CENTERNESS_ON_REG: True
  CENTER_SAMPLING_RADIUS: 1.5
  NUM_CONVS: 4
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 144000
  STEPS: (96000, 132000)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 4000
INPUT:
  TRANSFORM: "ResizeTransform"
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "output/pascal_voc/fcos_resnet_18_fpn_3x"
