_BASE_: "../Base-FCOS.yaml"
MODEL:
  WEIGHTS: "torchvision://ShuffleNet-V2-1.0"
  NUM_CLASSES: 20
  BACKBONE:
    NAME: "ShuffleNet-V2-1.0"
    OUT_FEATURES: ["stage2", "stage3", "conv5"]
FPN:
  IN_FEATURES: ["stage2", "stage3", "conv5"]
  TOP_BLOCK:
    NAME: "LastLevelP6P7"
    IN_FEATURE: "p5"
FCOS:
  NORM_REG_TARGETS: True
  CENTERNESS_ON_REG: True
  CENTER_SAMPLING_RADIUS: 1.5
  NUM_CONVS: 4
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 48000
  STEPS: (32000, 44000)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 4000
INPUT:
  TRANSFORM: "ResizeWithPaddingTransform"
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "output/pascal_voc/fcos_shufflenet_v2_1_0_fpn_1x"
