_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "torchvision://MobileNet-V2-1.0"
  BACKBONE:
    NAME: "MobileNet-V2-1.0"
    OUT_FEATURES: ["6", "13", "18"]
  NUM_CLASSES: 20
MOBILENET_V2:
  NORM: "BN"
FPN:
  IN_FEATURES: ["6", "13", "18"]
  TOP_BLOCK:
    IN_FEATURE: ("18")
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 144000
  STEPS: (96000, 132000)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 4000
INPUT:
  TRANSFORM: "ResizeTransform"
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "output/pascal_voc/retinanet_mobilenet_v2_1_0_fpn_3x"
