_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  NUM_CLASSES: 20
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  MAX_ITER: 144000
  STEPS: (96000, 132000)
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 4000
INPUT:
  MIN_SIZE_TRAIN: (512, 640, 800)
  MIN_SIZE_TEST: 800
OUTPUT_DIR: "output/pascal_voc/retinanet_resnet_50_fpn_3x"
